<?php

namespace AppBundle\Repository;

/**
 * accountStatementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class accountStatementRepository extends \Doctrine\ORM\EntityRepository
{
}
