<?php

namespace AppBundle\Repository;

/**
 * ContentPrestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentPrestationRepository extends \Doctrine\ORM\EntityRepository
{
}
