<?php

namespace AppBundle\Repository;

/**
 * FactureTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
