<?php

namespace AppBundle\Repository;

/**
 * FormatFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormatFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
