<?php

namespace AppBundle\Repository;

/**
 * TypeFactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeFactureRepository extends \Doctrine\ORM\EntityRepository
{
}
