imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'bootstrap_3_layout.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: 'pierregourlat@gmail.com'
    password: 'tennisman'
    spool: { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "hello@aquanotes.com"
        sender_name: "aquanotes postman"

easy_admin:
    site_name: 'AIR DG - Facturation'
    formats:
        date: 'd/m/Y'
    entities:
        Factures:
            class: AppBundle\Entity\Facture
            controller: AppBundle\Controller\FactureController
            list:
                fields:
                     - {property: 'id', label: 'Numéro'}
                     - {property: 'creationDate', label: 'Crée le'}
                     - {property: 'lastUpdate', label: 'Mise à jour le'}
                     - client
                     - type
                     - {property: 'paid', label: 'Payée', type: 'boolean'}
                     - {property: 'total', label: 'Montant (en €)'}
                actions: [{name: 'remplirFacture',icon: 'edit', label: 'Contenu', title: 'Editer le contenu de la facture'}, {name: 'edit', label: 'Editer propriétés', title: 'Le changement de type efface le contenu'}, {name: 'generatePDF', label: 'PDF',icon: 'eye',title: 'Générer le pdf', target: __blank}]
            show:
                fields:
                     - {property: 'id', label: 'Numéro'}
                     - type
                     - {property: 'creationDate', label: 'Crée le'}
                     - {property: 'lastUpdate', label: 'Mise à jour le'}
                     - client
                     - {property: 'paid', label: 'Payée', type: 'boolean'}
            form:
                fields:
                    - {property: 'type', css_class: 'col-xs-4'}
                    - {property: 'client', css_class: 'col-xs-4'}
                    - {property: 'paid', label: 'Payée (cocher pour affirmer)', css_class: 'col-xs-4'}

        Clients:
            class: AppBundle\Entity\Client
            controller: AppBundle\Controller\FactureController
            form:
                title: 'Rentrer un client en base de données'
                fields:
                    - {property: 'name', label: 'Nom de la société', css_class: 'col-xs-9'}
                    - {property: 'headOfficeAddr', label: 'Adresse', css_class: 'col-xs-5'}
                    - {property: 'postalCode', label: 'Code postal', css_class: 'col-xs-5'}
                    - {property: 'city', label: 'Ville', css_class: 'col-xs-5'}
                    - {property: 'country', label: 'Pays', type: 'country', type_options: {data: 'FR'}, css_class: 'col-xs-5'}
                    - {property: 'societyNumber', label: 'Numero de société', css_class: 'col-xs-5'}
                    - {property: 'vatNumber', label: 'Numéro de TVA', css_class: 'col-xs-5'}
                    - {property: 'iban', label: 'IBAN', type_options: {required: false}, css_class: 'col-xs-5'}
                    - {property: 'bic', label: 'BIC', type_options: {required: false}, css_class: 'col-xs-5'}
                    - {property: 'contactPerson', label: 'Personne à contacter', css_class: 'col-xs-3'}
                    - {property: 'email', label: 'Email', css_class: 'col-xs-3'}
                    - {property: 'phoneNumber', label: 'Téléphone', css_class: 'col-xs-3'}
            edit:
                title: "Mettre à jour un client"
            list:
                actions: [{name: 'edit', icon: 'edit', label: 'Editer', title: 'Modifier client'}, '-delete', '-show']
                fields:
                    - {property: 'name', label: 'Nom'}
                    - {property: 'city', label: 'Ville'}
                    - {property: 'country', label: 'Pays'}
                    - {property: 'email'}
                    - {property: 'phoneNumber', label: 'Telephone'}
                    - {property: 'contactPerson', label: 'Contact dans la société'}
                    - tvaIndex
            show:
                actions: ['-delete']

        Administrateurs:
            class: AppBundle\Entity\User
            controller: AppBundle\Controller\UserController
            edit:
                fields:
                    - { property: 'username', label: "Nom d'utilisateur", css_class: 'col-xs-4' }
                    - {property: 'email', css_class: 'col-xs-4'}
                    - { property: 'roles',  type: 'choice', type_options: {multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' }}, css_class: 'col-xs-4'}
            new:
                fields:
                    - { property: 'username', label: "Nom d'utilisateur", css_class: 'col-xs-4' }
                    - { property: 'plainPassword', label: 'Mot de passe', type: 'text', css_class: 'col-xs-4'}
                    - {property: 'email', css_class: 'col-xs-4'}
                    - { property: 'roles',  type: 'choice', type_options: {multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' }}, css_class: 'col-xs-2'}
                title: 'Créer un nouvel administrateur'
            list:
                actions: [{name: 'edit', icon: 'edit', label: 'Editer', title: 'Modifier compte'}]
                fields:
                    - { property: 'username', label: "Nom d'utilisateur" }
                    - email
                    - {property: 'enabled', label: 'Activé'}
            show:
                fields:
                    - { property: 'username', label: "Nom d'utilisateur" }
                    - email
                    - { property: 'enabled', label: "Activé" }
                    - { property: 'lastLogin', label: "Dernière connexion" }
                    - roles

        Vols:
            class: AppBundle\Entity\Flight

        Prestations:
            class: AppBundle\Entity\ContentPrestation
            controller: AppBundle\Controller\UserController
            form:
                fields:
                    - startDate
                    - endDate
                    - unitPrice

        Maintenance:
            class: AppBundle\Entity\maintenanceItem
            controller: AppBundle\Controller\UserController
            disabled_actions: [list]

        Extrait_Compte:
            class: AppBundle\Entity\accountStatement
            controller: AppBundle\Controller\FactureController
            list:
                actions: [{name: 'generateAccountPDF', label: 'PDF',icon: 'eye',title: 'Générer le pdf', target: __blank}, {name: 'edit', icon: 'edit', label: 'Editer'}]
            new:
                fields:
                    - {property: 'name', label: 'Nom', css_class: 'col-xs-5'}
                    - {property: 'client', label: 'Nom', css_class: 'col-xs-5'}
            edit:
                fields:
                    - {property: 'name', label: 'Nom', css_class: 'col-xs-5'}
                    - {property: 'client', label: 'Client', css_class: 'col-xs-5'}
                    - { property: 'factures', type: 'entity', css_class: 'col-xs-8' }

    design:
        brand_color: '#0929DE'
        color_scheme: 'dark'
        form_theme:
            - 'vertical'
        assets:
            favicon: '..\..\doc\images\icon.png'
